export const POST_COMMENT_CHANGE = 'POST_COMMENT_CHANGE'


export const POST_COMMENT_ADD_REQUEST = 'POST_COMMENT_ADD_REQUEST'
export const POST_COMMENT_ADD_SUCCESS = 'POST_COMMENT_ADD_SUCCESS'
export const POST_COMMENT_ADD_FAIL = 'POST_COMMENT_ADD_FAIL'

export const POST_COMMENTS_GET_REQUEST = 'POST_COMMENTS_GET_REQUEST'
export const POST_COMMENTS_GET_SUCCESS = 'POST_COMMENTS_GET_SUCCESS'
export const POST_COMMENTS_GET_FAIL = 'POST_COMMENTS_GET_FAIL'

export const POST_REPLIES_GET_REQUEST = 'POST_REPLIES_GET_REQUEST'
export const POST_REPLIES_GET_SUCCESS = 'POST_REPLIES_GET_SUCCESS'
export const POST_REPLIES_GET_FAIL = 'POST_REPLIES_GET_FAIL'

export const POST_COMMENT_UPDATE_REQUEST = 'POST_COMMENT_UPDATE_REQUEST'
export const POST_COMMENT_UPDATE_SUCCESS = 'POST_COMMENT_UPDATE_SUCCESS'
export const POST_COMMENT_UPDATE_FAIL = 'POST_COMMENT_UPDATE_FAIL'

export const POST_COMMENT_DELETE_REQUEST = 'POST_COMMENT_DELETE_REQUEST'
export const POST_COMMENT_DELETE_SUCCESS = 'POST_COMMENT_DELETE_SUCCESS'
export const POST_COMMENT_DELETE_FAIL = 'POST_COMMENT_DELETE_FAIL'