export const POST_ADD_REQUEST = 'POST_ADD_REQUEST'
export const POST_ADD_SUCCESS = 'POST_ADD_SUCCESS'
export const POST_ADD_FAIL = 'POST_ADD_FAIL'

export const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST'
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS'
export const POST_DELETE_FAIL = 'POST_DELETE_FAIL'

export const POST_GET_REQUEST = 'POST_GET_REQUEST'
export const POST_GET_SUCCESS = 'POST_GET_SUCCESS'
export const POST_GET_FAIL = 'POST_GET_FAIL'

export const POST_TITLE_LIST_REQUEST = 'POST_TITLE_LIST_REQUEST'
export const POST_TITLE_LIST_SUCCESS = 'POST_TITLE_LIST_SUCCESS'
export const POST_TITLE_LIST_FAIL = 'POST_TITLE_LIST_FAIL'

export const POST_SUGGEST_CHANGES_REQUEST = 'POST_SUGGEST_CHANGES_REQUEST'
export const POST_SUGGEST_CHANGES_SUCCESS = 'POST_SUGGEST_CHANGES_SUCCESS'
export const POST_SUGGEST_CHANGES_FAIL = 'POST_SUGGEST_CHANGES_FAIL'

export const POST_EDITOR_CHANGE = 'POST_EDITOR_CHANGE'
export const POST_EDITOR_TITLE_CHANGE = 'POST_EDITOR_TITLE_CHANGE'

export const POST_GET_CHANGES_REQUEST = 'POST_GET_CHANGES_REQUEST'
export const POST_GET_CHANGES_SUCCESS = 'POST_GET_CHANGES_SUCCESS'
export const POST_GET_CHANGES_FAIL = 'POST_GET_CHANGES_FAIL'

export const POST_GET_CHANGE_REQUEST = 'POST_GET_CHANGE_REQUEST'
export const POST_GET_CHANGE_SUCCESS = 'POST_GET_CHANGE_SUCCESS'
export const POST_GET_CHANGE_FAIL = 'POST_GET_CHANGE_FAIL'

export const POST_UPDATE_CHANGES_REQUEST = 'POST_UPDATE_CHANGES_REQUEST'
export const POST_UPDATE_CHANGES_SUCCESS = 'POST_UPDATE_CHANGES_SUCCESS'
export const POST_DIFFERENCES_RESET = 'POST_DIFFERENCES_RESET'
export const POST_UPDATE_CHANGES_FAIL = 'POST_UPDATE_CHANGES_FAIL'