export const TEST_GET_REQUEST = 'TEST_GET_REQUEST'
export const TEST_GET_SUCCESS = 'TEST_GET_SUCCESS'
export const TEST_GET_FAIL = 'TEST_GET_FAIL'

export const TEST_UPDATE_REQUEST = 'TEST_UPDATE_REQUEST'
export const TEST_UPDATE_SUCCESS = 'TEST_UPDATE_SUCCESS'
export const TEST_UPDATE_FAIL = 'TEST_UPDATE_FAIL'

export const TEST_CHECK_REQUEST = 'TEST_CHECK_REQUEST'
export const TEST_CHECK_SUCCESS = 'TEST_CHECK_SUCCESS'
export const TEST_CHECK_FAIL = 'TEST_CHECK_FAIL'

export const TEST_GET_RESULT_REQUEST = 'TEST_GET_RESULT_REQUEST'
export const TEST_GET_RESULT_SUCCESS = 'TEST_GET_RESULT_SUCCESS'
export const TEST_GET_RESULT_FAIL = 'TEST_GET_RESULT_FAIL'

export const TEST_GET_ALL_RESULTS_REQUEST = 'TEST_GET_ALL_RESULTS_REQUEST'
export const TEST_GET_ALL_RESULTS_SUCCESS = 'TEST_GET_ALL_RESULTS_SUCCESS'
export const TEST_GET_ALL_RESULTS_FAIL = 'TEST_GET_ALL_RESULTS_FAIL'

export const TEST_UPDATE_RESULT_REQUEST = 'TEST_UPDATE_RESULT_REQUEST'
export const TEST_UPDATE_RESULT_SUCCESS = 'TEST_UPDATE_RESULT_SUCCESS'
export const TEST_UPDATE_RESULT_FAIL = 'TEST_UPDATE_RESULT_FAIL'

export const RESULT_RESET = 'RESULT_RESET'
export const ALL_RESULTS_RESET = 'ALL_RESULTS_RESET'

export const TEST_CREATE_REQUEST = 'TEST_CREATE_REQUEST'
export const TEST_CREATE_SUCCESS = 'TEST_CREATE_SUCCESS'
export const TEST_CREATE_FAIL = 'TEST_CREATE_FAIL'

export const TEST_ADD_VARIANT = 'TEST_ADD_VARIANT'
export const TEST_DELETE_VARIANT = 'TEST_DELETE_VARIANT'
export const TEST_ADD_QUESTION = 'TEST_ADD_QUESTION'
export const TEST_DELETE_QUESTION = 'TEST_DELETE_QUESTION'

export const TEST_QUESTION_TITLE_CHANGE = 'TEST_QUESTION_TITLE_CHANGE'
export const TEST_VARIANT_TITLE_CHANGE = 'TEST_VARIANT_TITLE_CHANGE'
export const TEST_SCORE_CHANGE = 'TEST_SCORE_CHANGE'
export const TEST_IS_ANSWER_CHANGE = 'TEST_IS_ANSWER_CHANGE'